# -*- coding: utf-8 -*-
"""Copia de _Señales De Energia Y De Potencia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1ar34yrswzcXpYTGrq5623Yc2TVkQAF

# Señales de energía y potencia

Las señales pueden clasificarse como de energía o de potencia.

Los conceptos de energía y potencia son empleados para la generalización de métricas que permitirán tomar decisiones de convergencia en distintos tipos de análisis en espacios $L^{2}$.

---



## Señales de energía

Se dice que una señal es de energía, si su energía total $E_x$ converge, es decir:

$$
0< E_x < \infty. \tag{1}
$$

Para el caso de una señal $x(t)$ contínua, su energía total es calculada como:

$$
E_x = \|x(t) \|_2^2 = \int_{-\infty}^{\infty} |x(t)|^{2}~dt,  \tag{2}
$$
donde la [norma-2](https://en.wikipedia.org/wiki/Norm_(mathematics)) de la señal $x(t)$ se denota por: $\|x(t) \|_2^2.$ En el mismo sentido, la energía total de la función discreta $x[n]$, es:

$$
E_x = \|x[n] \|_2^2 = \sum_{n=-\infty}^{\infty} |x[n]|^{2}  \tag{3}
$$

Tomando en cuenta que la energía de una señal en un intervalo de tiempo finito $T$ es:

$$
E_T = \int_T |x(t)|^{2}~dt. \tag{4}
$$

La energía total de la señal puede expresarse en terminos del siguiente límite:

$$
E_x = \lim_{T \to \infty} E_T \tag{5}
$$

Para las señales discretas,

$$
E_N = \sum_{n=-N}^{N} |x[n]|^{2} \tag{6}
$$

Y la energía total de $x[n]$ es:

$$
E_x = \lim_{N \to \infty} E_N \tag{7}
$$

## Señales de potencia

Por otro lado, una señal se clasifica como de potencia, si su potencia media $\bar{P}_x$ converge, esto es:

$$
0< \bar{P}_x < \infty \tag{8}
$$

Para el caso de una señal $x(t)$  continua, su potencia media se calcula a partir de la siguiente expresión.

$$
\bar{P}_x = \lim_{T \to \infty} \frac{1}{T} \int_T |x(t)|^{2}~dt  \tag{9}
$$

Si $x(t)$ resulta ser periódica, la ecuación anterior puede reescribirse de la siguiente manera:

$$
\bar{P}_x = \lim_{k \to \infty} \frac{1}{k~T_0}~k \int_0^{T_0} |x(t)|^{2}~dt \tag{10}
$$

Donde $T_0$ es el periodo fundamental de la señal, con lo cual se logra hacer una analogía de la ecuación inicial de potencia llevando las repeticiones al infinito, obteniendo el siguiente resultado:

$$
\bar{P}_x = \frac{1}{T_0} \int_0^{T_0} |x(t)|^{2}~dt \tag{11}
$$

Para el caso de una señal discreta $x[n]$, su potencia media está definida por:

$$
\bar{P}_x = \lim_{N \to \infty} \frac{1}{2N+1} \sum_{n=-N}^{N} |x[n]|^{2}  \tag{12}
$$

De igual manera, si $x[n]$ resulta ser periódica, su potencia media estará dada por:

$$
\bar{P}_ x = \frac{1}{N_0} \sum_{n=0}^{N_0-1} |x_[n]|^{2} \tag{13}
$$

Donde $N_0$ es el número mínimo de muestras para el cual la señal $x[n]$ se repite.

La potencia media también se puede expresar en términos de la energía de la señal de la siguiente forma:

* Caso continuo

$$
\bar{P}_x = \lim_{T \to \infty} \frac{1}{T}~E_T \tag{14}
$$

* Caso discreto

$$
\bar{P}_x = \lim_{N \to \infty} \frac{1}{2N+1}~E_N \tag{15}
$$

De lo anterior se puede concluir que:

**-**Si la energía de la señal es finita, entonces su potencia es cero.

**-**Si la señal tiene energía infinita, su potencia puede ser finita o infinita.

**-**Si la potencia de la señal es finita, su energía es infinita.

## Ejemplo 1

Determine el concepto de potencia media a partir de la potencia instantánea disipada por una resistencia de $1 \Omega$.
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

fig, ax = plt.subplots(1, figsize=(8, 10))
ax.axvline(0.4, 0.8, 1, color="black", linewidth=5)
ax.axvline(0.4, 0, 0.2, color="black", linewidth=5)
rect = mpatches.Rectangle([0.2, 0.2], 0.4, 0.6, edgecolor="black", facecolor="white", linewidth=5)
ax.add_patch(rect)
ax.arrow(0.7, 0.2, 0, 0.6, width=0.005, length_includes_head=True, head_width=0.05, facecolor="black")
ax.arrow(0.4, 1, 0, -0.15, width=0.005, length_includes_head=True, head_width=0.05, facecolor="black")
ax.text(0.4, 0.5, r'$R=1 \Omega$', fontsize = 45, horizontalalignment='center')
ax.text(0.3, 0.9, r'$i(t)$', fontsize = 45, horizontalalignment='center')
ax.text(0.8, 0.5, r'$v(t)$', fontsize = 45, horizontalalignment='center')
ax.grid()
ax.set_axis_off()
fig.show()

"""La potencia instantánea $p(t)$ para el elemento resistivo está dada por la siguiente ecuación:

$$
p(t) = v(t) \cdot i(t) = R \cdot i(t)^{2}
$$

Evaluando en $R = 1 \Omega$,

$$
p(t) = i(t)^{2}
$$

La potencia media de la señal de corriente en un intervalo de tiempo $T$ es entonces la siguiente:

$$
\bar{P}_i = \frac{1}{T} \int_0^{T} i(t)^{2}~dt
$$

Para el caso en el que $i(t)$ coincide con una señal sinusoidal,

$$
\bar{P}_i = \frac{1}{T_0} \int_0^{T_0} \left( I_{\max}~\sin(w_0t+\theta) \right)^{2}~dt\\
\bar{P}_i = \frac{I_{\max}^{2}}{2}
$$

Lo que es equivalente al cuadrado del [valor eficaz](https://en.wikipedia.org/wiki/Root_mean_square) de la señal.

$$
I_{RMS} = \frac{I_{\max}}{\sqrt{2}}
$$
"""

from sympy import * #importar todo sympy
init_printing()
t, I_max = symbols('t, I_max', real = True)
w = symbols('w', real = True, nonzero = True)
T0 = 2*pi/w
x = I_max*sin(w*t)
P = integrate(x**2, (t, 0, T0)) /T0
print('La potencia media de la señal es:')
P

"""La siguiente figura muestra la potencia media  e instantánea de la señal de corriente $4\sin(2 \pi t)$, cuando circula a través de una resistencia de 1 Ohm."""

import warnings
warnings.filterwarnings("ignore")

w0 = 2*pi
T0 = T0.subs(w, w0)
sig = 4*sin(w0*t)
p_ins = sig ** 2
P = integrate(sig**2, (t, 0, T0)) /T0 #funcion de potencia media

t_limits = (t, 0, 3)
ylim=[-5, 18]
p1 = plot(sig, t_limits, ylim=ylim,show = False, line_color = 'orange', legend = True)
p2 = plot(p_ins, t_limits, ylim=ylim, show = False, legend = True)
p3 = plot(P, t_limits, ylim=ylim, show = False, line_color = 'green', legend = True)
p1.extend(p2)
p1.extend(p3)
p1.show()

"""## Ejercicio 1

Graficar la potencia media de una impedancia $R+jwL$, cuándo es excitada por una fuente sinusoidal.

Graficar la potencia media de una impedancia $R-j\frac{1}{wC} $, cuándo es excitada por una fuente sinusoidal.

Ver cuaderno [https://github.com/amalvarezme/SenalesSistemas/blob/master/1_IntroduccionSyS/6_Potencia_Circutios.ipynb](https://github.com/amalvarezme/SenalesSistemas/blob/master/1_IntroduccionSyS/6_Potencia_Circutios.ipynb) para repaso conceptos básicos potencia en circuitos.
"""

#para R+jwL
t, R, L, Vm = symbols('t R L Vm', real=True, positive=True)
w0 = 2 * pi
T0 = 2 * pi / w0


Z = R + I * w0 * L
I_t = Vm / Z
I_mag2 = Abs(I_t)**2


P = integrate(I_mag2, (t, 0, T0)) / T0


R_val = 10
L_val = 0.1
Vm_val = 10
P_val = P.subs({R: R_val, L: L_val, Vm: Vm_val})


ylim = [0, 10]
p1 = plot(P_val, (t, 0, 3), ylim=ylim, line_color='blue', ylabel="Potencia Media", show=True)

"""## Ejemplo 2

Para el caso de una señal sinusoidal de amplitud $A$ y periodo fundamental $T_0$ tal que:
$$
v(t) = A\cos(w_0t), ~~~ w_0 = \frac{2\pi}{T_0}
$$

Determinar su potencia media y energía total.

$$
\bar{P}_v = \frac{1}{T_0} \int_0^{T_0} |A\cos(w_0t)|^{2}~dt\\
\bar{P}_v = \frac{A^{2}}{T_0} \left[\int_0^{T0} \frac{1}{2} ~dt + \int_0^{T0} \frac{\cos(2w_0t)}{2} ~dt  \right]\\
\bar{P}_v = \frac{A^{2}}{2}
$$

Debido a que la potencia de la señal es finita (siempre y cuando $A<\infty$), su energía total es infinita.

$$
E_v \to \infty
$$
"""

t = symbols('t', real = True)
w, A = symbols('w, A', real = True, nonzero = True, nonnegative = True)
T0 = 2*pi/w
x = A*cos(w*t)
Pv = integrate(x**2, (t, 0, T0)) /T0
print('La potencia media de la señal es:')
Pv

T = symbols('T', real = True)
Ev = integrate(x**2, (t, -oo, oo))
print('\nLa energía total de la señal es:')
Ev

"""## Ejercicio 2

Discuta el concepto de valor RMS de una señal a partir de su potencia media. [Ver conceptos RMS](https://en.wikipedia.org/wiki/Root_mean_square).

**El valor RMS**

este valor nos ayuda a ver la cantidad de potencia que consume una carga con mayor claridad, puesto que en corriente alterna las señales son mas dificiles de analizar que en continua, empezando por el hecho de que el valor pico de la señal,no es el valor de corriente o tension que recibe la carga exactamente, tener una manera de visualizar estos valores de una manera mas cerca a la realidad, es sumamente util

## Ejemplo 3

Para el caso de la señal $x(t) = e^{-\alpha t}u(t)$ con $\alpha > 0$, hallar su energía y potencia media.

$$
E_x = \int_{-\infty}^{\infty} |e^{-\alpha t}u(t)|^{2}~dt\\
E_x = \int_{0}^{\infty} e^{-2\alpha t}~dt\\
E_x = -\frac{1}{2\alpha}~ e^{-2\alpha t}~\Big|_0^\infty\\
E_x = \frac{1}{2\alpha}
$$

$$
\bar{P}_x = \lim_{T \to \infty} \frac{1}{T} \int_{-\frac{T}{2}}^{\frac{T}{2}} |e^{-\alpha t}u(t)|^{2}~dt\\
\bar{P}_x = \lim_{T \to \infty} \frac{1}{T} \int_{0}^{\frac{T}{2}} e^{-2\alpha t}~dt\\
\bar{P}_x = \lim_{T \to \infty} \frac{1}{T} \left[  -\frac{1}{2\alpha}~ e^{-2\alpha t}~\Big|_0^\frac{T}{2} \right]\\
\bar{P}_x = \lim_{T \to \infty} \frac{1}{T} \left[  -\frac{1}{2\alpha}~ e^{-\alpha T} + \frac{1}{2\alpha} \right]\\
\bar{P}_x = 0
$$
"""

from sympy import exp
t = symbols('t', Real = True)
a = symbols('a', Real = True, nonzero = True, nonnegative = True)
x = exp(-a*t)
E = integrate(x**2, (t, 0, oo))
print('La energía total de la señal es:')
E

T = symbols('T', Real = True)
P = limit(integrate(x**2, (t, 0, T/2)) / T, T, oo)
print('\nLa potencia media de la señal es:')
P

"""## Ejemplo 4

Determine la potencia y energía de la señal escalón unitario discreta $u[n]$.

$$
\bar{P} = \lim_{N \to \infty} \frac{1}{2N+1} \sum_{n=-N}^{N} |u[n]|^{2}\\
\bar{P} = \lim_{N \to \infty} \frac{1}{2N+1} \sum_{n=0}^{N} 1\\
\bar{P} = \lim_{N \to \infty} \frac{N+1}{2N+1}\\
\bar{P} = \frac{1}{2}
$$

Debido a que la potencia media de la señal es finita, su energía total es infinita.

$$
E \to \infty
$$

## Ejercicio 3

Finalmente, clasifique la señal $x(t) = e^{-\alpha t}~t$ como de energía o de potencia. *Compruebe el resultado solucionando la integral por partes.*

Ayuda: declare la función en la variable **x** en el siguiente bloque de código como se muestra a continuación.

```
x = exp(-a*t)*t
```
"""

x = exp(-a*t)*t
E = integrate(x**2, (t, -oo, oo))
print('La energía total de la señal es:')
print(E)
P = limit(integrate(x**2, (t, -T/2, T/2)) / T, T, oo)
print('\nLa potencia media de la señal es:')
P

"""La funcion mencionada no es de energia ni de potencia, puesto que ninguna de las dos converge

##Ejercicio 4

La distancia entre dos señales $x_1(t)$ y $x_2(t)$ se puede dar en términos de la potencia media de la diferencia entre ellas; es decir, la potencia media del error.

$$
d(x_1, x_2) = \bar{P}_{x_1-x_2}=\lim_{T \to \infty} \frac{1}{T} \int_T |x_1(t)-x_2(t)|^{2}~dt
$$

Sea $x_1(t)$ y $x_2(t$) dos señales periódicas de periodo fundamental $T_0$ como se muestra a continuación.

$$
x_1(t) = \cos(w_0t), ~~~ w_0 = \frac{2\pi}{T_0}\\
x_2(t)= \left\{ \begin{array}{lcc}
             ~~~1 &   si  & 0 \leq t < \frac{T}{4} \\
             \\ -1 &  si &  \frac{T}{4} \leq t < \frac{3T}{4} \\
             \\ ~~~1 &  si  & \frac{3T}{4} \leq t < T
             \end{array}
   \right.
$$

Determine la distancia entre las dos señales.

## Ejercicio 5

Demostrar que la norma al cuadrado de una señal equivale a su energía.

**Copyright**

The notebook is provided as [Open Educational Resource](https://de.wikipedia.org/wiki/Open_Educational_Resources). Feel free to use the notebook for your own educational purposes. The text is licensed under [Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/), the code of the IPython examples under the [MIT license](https://opensource.org/licenses/MIT). Please attribute the work as follows: *Signals and Systems* by Sascha Spors.
"""